version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_name}}"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: django
    versions:
    - ">=4.3"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/{{cookiecutter.project_name}}"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: python
    versions:
    - ">=3.13"
  commit-message:
    prefix: chore
    include: scope
