repos:
  - repo: local
    hooks:
      - id: ruff-format
        stages: [commit]
        name: ruff-format
        language: system
        entry: ruff format .
        types: [python]
      - id: ruff-check
        stages: [commit]
        name: ruff-check
        language: system
        entry: ruff check . --show-source --fix
        types: [python]
      - id: gitlint
        stages: [commit-msg]
        name: gitlint
        description: Validate commit lint
        entry: gitlint --msg-filename
        language: system
