---
services:
  db:
    environment:
      - POSTGRES_PASSWORD={{cookiecutter.project_name}}
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    environment:
      - ENV=dev
      #  - OIDC_VERIFY_SSL=False
      - OIDC_OP_USER_ENDPOINT=https://{{cookiecutter.project_name}}.local/auth/realms/{{cookiecutter.project_name}}/protocol/openid-connect/userinfo
