services:

  db:
    environment:
      - POSTGRES_PASSWORD={{cookiecutter.project_name}}
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      args:
        INSTALL_DEV_DEPENDENCIES: "true"
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it db:5432 -- poetry run ./manage.py migrate && poetry run ./manage.py runserver 0.0.0.0:8000",
      ]
    environment:
      - ENV=dev
      #  - OIDC_VERIFY_SSL=False
      - OIDC_OP_USER_ENDPOINT=https://{{cookiecutter.project_name}}.local/auth/realms/{{cookiecutter.project_name}}/protocol/openid-connect/userinfo
