name: Tests

on:
  push:
  pull_request:

jobs:
  standard-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install cookiecutter
        run: pip install cookiecutter
      - name: Test project
        run: make test
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.9'
      - name: Install gitlint
        run: pip install gitlint
      - name: Run gitlint
        run: gitlint --contrib contrib-title-conventional-commits --ignore B1,B5,B6
